Repository DucTran999/fashion-shop, pull requests merged in 2023-06, with the labels that each got.

#51 #50 - fix: disabled react, redux devtools on production.
  admin/src/index.js
  admin/src/redux/store.js
  admin/src/utils/disableReactDevtools.js
  client/.gitignore
  client/src/features/store.js
  client/src/index.js
  client/src/utils/disableReactDevtools.js
Labels: bug, resolved, security

#54 #53 - fix: add cors config for socket io
  server/src/api/utils/init.socket.js
  server/src/api/v1/products/product.model.js
  server/src/api/v1/sessions/session.controller.js
  server/src/app.js
  server/src/configs/cors.config.js
Labels: bug, feature, resolved

#68 #66 - refactor(ui): Improve Login Page for better user experience
  client/src/components/Card/ProductCard.module.scss
  client/src/components/Carousel/Carousel.jsx
  client/src/components/Wrapper/AuthWrapper.scss
  client/src/layouts/AuthLayout/AuthLayout.module.scss
  client/src/layouts/AuthLayout/index.jsx
Labels: enhancement, style

#71 #70 [Refactor] api for uploading image
  admin/src/api/url.init.js
  admin/src/components/UploadImageForm/index.jsx
  server/package-lock.json
  server/package.json
  server/src/api/v1/router.js
  server/src/api/v1/upload/upload.config.js
  server/src/api/v1/upload/upload.controller.js
  server/src/api/v1/upload/upload.route.js
  server/src/api/v1/upload/upload.validate.js
  server/yarn.lock
Labels: refactor, api

#72 chore: update endpoint, method name, return status code by new convetion
  server/src/api/v1/category/category.controller.js
  server/src/api/v1/category/category.model.js
  server/src/api/v1/category/category.route.js
  server/src/api/v1/category/category.validation.js
  server/src/api/v1/notification/messageTemplate.js
  server/src/api/v1/notification/notification.controller.js
  server/src/api/v1/notification/notification.model.js
  server/src/api/v1/notification/notification.route.js
  server/src/api/v1/notification/notification.service.js
  server/src/api/v1/notification/notification.validation.js
  server/src/api/v1/order/order.controller.js
  server/src/api/v1/order/order.model.js
  server/src/api/v1/order/order.route.js
  server/src/api/v1/order/order.service.js
  server/src/api/v1/order/order.validation.js
  server/src/api/v1/payment/payment.model.js
  server/src/api/v1/products/product.service.js
  server/src/api/v1/router.js
  server/src/api/v1/session/session.controller.js
  server/src/api/v1/session/session.route.js
  server/src/api/v1/session/session.service.js
  server/src/api/v1/session/session.validator.js
  server/src/api/v1/size/size.controller.js
  server/src/api/v1/size/size.model.js
  server/src/api/v1/size/size.route.js
  server/src/api/v1/state/state.model.js
  server/src/api/v1/user/user.controller.js
  server/src/api/v1/user/user.model.js
  server/src/api/v1/user/user.repository.js
  server/src/api/v1/user/user.route.js
  server/src/api/v1/user/user.services.js
  server/src/api/v1/user/user.validation.js
Labels: refactor, api
