Repository DucTran999/fashion-shop, pull requests merged in 2023-07, with the labels that each got.

#74 [Feature Request] new registration need to verify email
  client/src/App.js
  client/src/assets/icons/index.js
  client/src/features/auth/apiRequest.js
  client/src/features/auth/authSlice.js
  client/src/features/user/userRequest.js
  client/src/features/user/userSlice.js
  client/src/pages/Auth/RegisterPage.jsx
  client/src/pages/VerificationEmail/VerificationEmail.module.scss
  client/src/pages/VerificationEmail/index.jsx
  client/src/pages/index.js
  server/package-lock.json
  server/package.json
  server/src/api/utils/constVariable.js
  server/src/api/utils/formatData.js
  server/src/api/utils/init.socket.js
  server/src/api/v1/email/emailSender.js
  server/src/api/v1/email/templateEmail.js
  server/src/api/v1/helpers/helper.socket.js
  server/src/api/v1/session/session.service.js
  server/src/api/v1/user/user.controller.js
  server/src/api/v1/user/user.repository.js
  server/src/api/v1/user/user.route.js
  server/src/api/v1/user/user.services.js
  server/yarn.lock
Labels: enhancement, feature, security, api

#77 Lockout account if too many failed login attempt
  client/src/components/Logo/Logo.jsx
  client/src/components/Logo/Logo.scss
  client/src/components/Logo/index.jsx
  client/src/components/Modal/PopupContainer.module.scss
  client/src/components/Modal/PopupVariant.module.scss
  client/src/features/auth/apiRequest.js
  client/src/layouts/Header/SimpleHeader.jsx
  client/src/layouts/Header/SimpleHeader.module.scss
  client/src/layouts/PrimaryHeader/ViewDesktop.jsx
  client/src/layouts/PrimaryHeader/ViewMobile.jsx
  client/src/layouts/PrimaryHeader/ViewTablet.jsx
  server/src/api/utils/constVariable.js
  server/src/api/v1/email/emailSender.js
  server/src/api/v1/email/templateEmail.js
  server/src/api/v1/session/session.controller.js
  server/src/api/v1/session/session.model.js
  server/src/api/v1/session/session.service.js
  server/src/api/v1/user/user.controller.js
  server/src/api/v1/user/user.repository.js
  server/src/api/v1/user/user.route.js
  server/src/api/v1/user/user.services.js
Labels: enhancement, security

#80 78 feature request strong password is must
  client/src/components/Input/InputErrorMessage.js
  client/src/pages/Auth/RegisterPage.jsx
  client/src/utils/Validator.js
  server/src/api/v1/user/user.validation.js
Labels: enhancement, security

#81 Release v1.2.0
  client/src/components/Input/InputErrorMessage.js
  client/src/components/Logo/Logo.jsx
  client/src/components/Logo/Logo.scss
  client/src/components/Logo/index.jsx
  client/src/components/Modal/PopupContainer.module.scss
  client/src/components/Modal/PopupVariant.module.scss
  client/src/features/auth/apiRequest.js
  client/src/layouts/Header/SimpleHeader.jsx
  client/src/layouts/Header/SimpleHeader.module.scss
  client/src/layouts/PrimaryHeader/ViewDesktop.jsx
  client/src/layouts/PrimaryHeader/ViewMobile.jsx
  client/src/layouts/PrimaryHeader/ViewTablet.jsx
  client/src/pages/Auth/RegisterPage.jsx
  client/src/utils/Validator.js
  server/src/api/utils/constVariable.js
  server/src/api/v1/email/emailSender.js
  server/src/api/v1/email/templateEmail.js
  server/src/api/v1/session/session.controller.js
  server/src/api/v1/session/session.model.js
  server/src/api/v1/session/session.service.js
  server/src/api/v1/user/user.controller.js
  server/src/api/v1/user/user.repository.js
  server/src/api/v1/user/user.route.js
  server/src/api/v1/user/user.services.js
  server/src/api/v1/user/user.validation.js
Labels: enhancement, security

#82 fix: missing call test function when validate with regex Uppercase
  client/src/utils/Validator.js
Labels: bug

#84 Fixes #83 Bug email verification to unlock account annoying user
  client/.env.example
  client/package-lock.json
  client/package.json
  client/src/api/init.url.js
  client/src/components/Modal/ModalContainer.jsx
  client/src/components/Modal/PopupVariant.jsx
  client/src/features/auth/apiRequest.js
  client/src/features/email/emailAction.js
  client/src/features/email/emailSlice.js
  client/src/features/store.js
  client/src/features/user/userRequest.js
  client/src/features/user/userSlice.js
  client/src/pages/Auth/LoginPage.jsx
  client/src/pages/Auth/RegisterPage.jsx
  client/src/pages/VerificationEmail/index.jsx
  client/src/utils/constVariable.js
  client/src/utils/delay.js
  client/src/utils/doStuff.js
  client/src/utils/helper.crypto.js
  client/yarn.lock
  server/.env.example
  server/src/api/utils/constVariable.js
  server/src/api/utils/crypto.js
  server/src/api/utils/normalizeData.js
  server/src/api/v1/email/email.controller.js
  server/src/api/v1/email/email.route.js
  server/src/api/v1/email/email.service.js
  server/src/api/v1/email/email.validation.js
  server/src/api/v1/email/emailSender.js
  server/src/api/v1/email/emailTokenManager.js
  server/src/api/v1/email/templateEmail.js
  server/src/api/v1/helpers/init.redis.client.js
  server/src/api/v1/helpers/init.smtp.js
  server/src/api/v1/products/product.service.js
  server/src/api/v1/router.js
  server/src/api/v1/session/session.service.js
  server/src/api/v1/session/session.validator.js
  server/src/api/v1/user/user.controller.js
  server/src/api/v1/user/user.repository.js
  server/src/api/v1/user/user.route.js
  server/src/api/v1/user/user.services.js
Labels: bug, security, api, crittical

#87 Improve High Availability using Rate Limiting and Caching (#85)
  client/src/pages/Auth/LoginPage.jsx
  client/src/pages/Auth/RegisterPage.jsx
  server/src/api/utils/formatData.js
  server/src/api/v1/email/email.controller.js
  server/src/api/v1/email/email.service.js
  server/src/api/v1/email/emailTokenManager.js
  server/src/api/v1/helpers/helper.ipMonitor.js
  server/src/api/v1/helpers/init.redis.client.js
  server/src/api/v1/middleware/cache.middleware.js
  server/src/api/v1/middleware/rateLimit.middleware.js
  server/src/api/v1/products/product.controller.js
  server/src/api/v1/products/product.route.js
  server/src/api/v1/products/products.validation.js
  server/src/api/v1/session/session.controller.js
  server/src/api/v1/session/session.route.js
  server/src/api/v1/session/session.validator.js
  server/src/api/v1/user/user.controller.js
  server/src/app.js
  server/src/middleware/ipFilter.js
Labels: enhancement, security, high availability

#89 Improve UI for Product Page (#88)
  client/src/features/auth/apiRequest.js
  client/src/features/cart/cartSlice.js
  client/src/features/getProduct/fetchRequest.js
  client/src/pages/Product/Product.module.scss
  client/src/pages/Product/ProductDetail.jsx
  client/src/pages/Product/index.jsx
  server/src/api/v1/products/product.controller.js
  server/src/api/v1/products/product.route.js
Labels: enhancement, ui

#96 refactor: reduce wait time to 800ms. (#92)
  client/src/pages/Product/ProductDetail.jsx
Labels: enhancement, ui

#98 Have struggled on installing the projects (#97)
  .gitignore
  README.md
  admin/.dockerignore
  admin/.env.example
  admin/Dockerfile
  admin/README.md
  admin/docker-compose.yml
  admin/yarn.lock
  adr/atlanashop_schema.sql
  client/.dockerignore
  client/.env.example
  client/Dockerfile
  client/docker-compose.yml
  client/yarn.lock
  server/.dockerignore
  server/.env.example
  server/.gitignore
  server/Dockerfile
  server/docker-compose.yml
  server/shared/atlanashop_db.sql
  server/src/api/v1/products/product.route.js
  server/yarn.lock
  setup.sh
Labels: documentation

#104 [Feature Request] Search Module (#103)
  client/src/App.js
  client/src/api/endpoint.js
  client/src/assets/icons/index.js
  client/src/assets/images/index.js
  client/src/assets/images/search/search.webp
  client/src/components/ScrollTopButton/ScrollTopButton.module.scss
  client/src/components/ScrollTopButton/index.jsx
  client/src/features/productList/productListAction.js
  client/src/features/productList/productListSlice.js
  client/src/features/store.js
  client/src/layouts/PrimaryHeader/Desktop/SubNavBar.jsx
  client/src/layouts/PrimaryHeader/Tablet/MenuDropDown.jsx
  client/src/layouts/PrimaryHeader/index.jsx
  client/src/pages/Category/index.jsx
  client/src/pages/Search/Common/SearchResult.jsx
  client/src/pages/Search/Common/SearchResult.module.scss
  client/src/pages/Search/Desktop/DesktopView.jsx
  client/src/pages/Search/Desktop/DesktopView.module.scss
  client/src/pages/Search/Mobile/MobileView.jsx
  client/src/pages/Search/Mobile/MobileView.module.scss
  client/src/pages/Search/Search.module.scss
  client/src/pages/Search/Tablet/TabletView.jsx
  client/src/pages/Search/Tablet/TabletView.module.scss
  client/src/pages/Search/index.jsx
  client/src/pages/WishList/index.jsx
  client/src/pages/index.js
  client/src/styles/_animation.scss
  client/src/utils/constVariable.js
  client/src/utils/formatData.js
  server/babel.config.json
  server/src/api/utils/constVariable.js
  server/src/api/utils/formatData.js
  server/src/api/v1/helpers/helper.cache.js
  server/src/api/v1/helpers/init.postgres.pool.js
  server/src/api/v1/router.js
  server/src/api/v1/search/analyzeSearchTerm.js
  server/src/api/v1/search/search.controller.js
  server/src/api/v1/search/search.model.js
  server/src/api/v1/search/search.route.js
  server/src/api/v1/search/search.service.js
  server/src/api/v1/search/search.test.js
  server/src/api/v1/search/search.validation.js
  server/src/middleware/errorHandler.js
Labels: feature, api, ui

#106 [Improve UI] New 404 Page (#105)
  client/src/assets/images/index.js
  client/src/assets/images/missingPage/missing404.png
  client/src/assets/images/missingPage/missing404.webp
  client/src/pages/MissingPage/MissingPage.module.scss
  client/src/pages/MissingPage/index.jsx
  client/src/pages/WishList/Common/EmptyWishlist.jsx
  client/src/pages/WishList/Common/EmptyWishlist.module.scss
Labels: enhancement, ui

#110 Release 1.4.1
  client/src/layouts/PrimaryHeader/PrimaryHeader.module.scss
  client/src/styles/_animation.scss
  server/src/api/utils/constVariable.js
  server/src/api/v1/email/email.controller.js
  server/src/api/v1/email/email.service.js
  server/src/api/v1/email/email.validation.js
  server/src/api/v1/email/emailBuilder.js
  server/src/api/v1/email/emailSender.js
  server/src/api/v1/email/emailTokenManager.js
  server/src/api/v1/email/templateEmail.js
  server/src/api/v1/helpers/helper.cache.js
  server/src/api/v1/helpers/init.postgres.pool.js
  server/src/api/v1/middleware/auth.middleware.js
  server/src/api/v1/search/search.model.js
  server/src/api/v1/search/search.service.js
  server/src/api/v1/search/search.test.js
  server/src/api/v1/search/searchTermAnalyzer.js
  server/src/api/v1/session/session.service.js
  server/src/api/v1/user/user.services.js
Labels: refactor, Release
